import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google"; 
import "./globals.css";
import Navbar from "@/Componant/Navbar";
import { ThemeProvider } from "@/components/ui/theme-provider";
import Footer from "@/Componant/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], 
  variable: "--font-poppins", 
});

export const metadata: Metadata = {
  title: "Echo Gpt",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased scroll-smooth`} 
    >
      
      <body className={`${poppins.className} min-h-full flex flex-col`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
             <Navbar></Navbar>
            {children}
            <Footer></Footer>
          </ThemeProvider>
        </body>
    </html>
  );
}